CREATE TABLE IF NOT EXISTS GAME_STATS(
	ID INTEGER PRIMARY KEY  AUTOINCREMENT,
    PLAY_DATE TEXT,
    SCORE INTEGER,
    ACCURACY REAL,
    AVG_REACTION REAL,
    HITS INTEGER,
    MISSES INTEGER,
    MAX_COMBO INTEGEREGER
);
